app:
  name: amiibos-aggregator
spring:
  application:
    name: ${app.name}
  config:
    import: consul:,vault://
  cloud:
    consul:
      enabled: true
      host: localhost
      port: 8500
      config:
        enabled: true
        format: YAML
        prefixes: ru/romanorlov
        data-key: data
        watch:
          wait-time: 15
          delay: 5000
        profile-separator: /
    vault:
      enabled: true
      scheme: http
      host: localhost
      port: 8200
      fail-fast: true
      authentication: token
      token: root
      kv:
        enabled: true
        default-context: ''
        backend: kv/app