services:
  postgres:
    image: postgres
    container_name: postgres-amiibos-aggregator
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: application_db
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  consul:
    image: hashicorp/consul
    container_name: consul-amiibos-aggregator
    hostname: localhost
    ports:
      - 8500:8500
    volumes:
      - ./local/bootstrap/consul:/tmp/bootstrap/
    command: -server -bootstrap -ui-dir /ui
    entrypoint: sh -c "/tmp/bootstrap/start.sh"

  vault:
    image: hashicorp/vault
    container_name: vault-amiibos-aggregator
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_API_ADDR: "http://0.0.0.0:8200"
    ports:
      - 8200:8200
    volumes:
      - ./local/bootstrap/vault:/vault/config
      - ./local/bootstrap/vault/volumes:/vault/file:rw
      - ./local/bootstrap/vault/policies:/vault/policies
      - ./local/bootstrap/vault/data:/vault/data
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -dev -dev-listen-address="0.0.0.0:8200" -dev-root-token-id="root"

  vault-init:
    container_name: vault-init-amiibos-aggregator
    image: hashicorp/vault
    volumes:
      - ./local/bootstrap/vault/vault-init.sh:/vault-init.sh
    depends_on:
      - vault
    restart: "no"
    entrypoint: sh -c "/vault-init.sh"
