services:
  postgres:
    image: postgres
    container_name: postgres-amiibo_aggregator
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: application_db
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
