app:
  name: SpringBootExample

spring:
  cloud:
    consul:
      config:
        enabled: false
    vault:
      enabled: false
  application:
    name: ${app.name}
  datasource:
    url: jdbc:postgresql://localhost:5432/application_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/db.changelog-master.yaml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  codec:
    max-in-memory-size: 10MB

client:
  connection-timeout: 5000
  response-timeout: 5000